server:
    port: 8760
spring:
    cloud:
        config:
            server:
                git:
                    clone-on-start: true
                    default-label: master
                    uri: file://C:/workspace/workspace-Intellij-IDEA/mestests/productcommanduser/config-files-properties
